Explaining `$this->factory->create();`
core23/DompdfBundle pull request #184
Opened 2021-01-07 15:03 UTC by ThomasLandauer

2021-01-07 16:04 UTC, ThomasLandauer commented
I also changed the "sample" setting to `defaultFont`, since `defaultPaperSize` isn't working (see https://github.com/nucleos/NucleosDompdfBundle/issues/1)

2021-01-08 20:21 UTC, core23 requested changes

2021-01-08 20:21 UTC, core23 commented on README.md
> +        $dompdf = $this->factory->create(); // Returns a `Dompdf\Dompdf` object
The `Returns ...` comment seems redundant to me

2021-01-08 20:21 UTC, core23 commented on README.md
> +        // `$response` is a `Symfony\Component\HttpFoundation\StreamedResponse`
Same here

2021-01-08 20:43 UTC, ThomasLandauer commented on README.md
> +        $dompdf = $this->factory->create(); // Returns a `Dompdf\Dompdf` object
Well, to me it wasn't clear what a method called `create()` could return ;-)

2021-01-08 20:44 UTC, ThomasLandauer commented on README.md
> +        // `$response` is a `Symfony\Component\HttpFoundation\StreamedResponse`
In this case it wasn't clear that it's a **Symfony** StreamedResponse.

2021-01-08 20:58 UTC, core23 commented on README.md
> +        // `$response` is a `Symfony\Component\HttpFoundation\StreamedResponse`
Then you should use `// @var Symfony\Component\HttpFoundation\StreamedResponse` as this is standard phpdoc for type information.

2021-01-08 21:00 UTC, core23 commented on README.md
> +        $dompdf = $this->factory->create(); // Returns a `Dompdf\Dompdf` object
This is just example code to get started. I would leave out anything special that a normal developer could not figure out itself.

2021-01-09 23:39 UTC, ThomasLandauer commented on README.md
> +        $dompdf = $this->factory->create(); // Returns a `Dompdf\Dompdf` object
If it's explained in README anybody can figure it out *before* installing it. Besides, one additional line here doesn't hurt anybody, and the `@var` annotation is a really nice solution :-)

2021-01-10 18:15 UTC, merged

2021-01-10 18:15 UTC, core23 commented
Thanks @ThomasLandauer